# Generated by Django 4.2.3 on 2023-08-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id_postal_operator', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('representante_legal', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
            ],
        ),
    ]
