# Generated by Django 4.2.3 on 2023-08-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_form_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fecha_emision',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
