# Generated by Django 4.2.3 on 2023-08-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_alter_form_fecha_emision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='fecha_emision',
        ),
    ]
