# Generated by Django 4.2.3 on 2023-08-10 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_remove_form_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
