# Generated by Django 4.2.3 on 2023-08-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_form_fecha_emision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='telefono',
            new_name='telefono_celular',
        ),
        migrations.AddField(
            model_name='form',
            name='telefono_fijo',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
