# Generated by Django 4.2.3 on 2023-08-17 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_rename_telefono_form_telefono_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id_period', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo_A',
            fields=[
                ('id_modulo_a', models.AutoField(primary_key=True, serialize=False)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.form')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.period')),
            ],
        ),
    ]
