# Generated by Django 4.2.3 on 2023-08-17 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_period_modulo_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteriaMes',
            fields=[
                ('id_paqueteria_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('enlace', models.CharField(blank=True, max_length=50)),
                ('modulo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.modulo_a')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosMes',
            fields=[
                ('id_documento_mes', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=20)),
                ('enlace', models.CharField(blank=True, max_length=50)),
                ('modulo_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.modulo_a')),
            ],
        ),
    ]
