# Generated by Django 4.2.3 on 2023-08-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_paqueteriames_documentosmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosmes',
            name='enlace',
        ),
        migrations.RemoveField(
            model_name='paqueteriames',
            name='enlace',
        ),
    ]
