# Generated by Django 4.2.3 on 2023-08-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_remove_documentosmes_enlace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('numero_de_documentos', models.IntegerField()),
                ('numero_de_paquetes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='paqueteriames',
            name='modulo_a',
        ),
        migrations.AlterUniqueTogether(
            name='modulo_a',
            unique_together={('periodo', 'operador')},
        ),
        migrations.DeleteModel(
            name='DocumentosMes',
        ),
        migrations.DeleteModel(
            name='PaqueteriaMes',
        ),
        migrations.AddField(
            model_name='envio',
            name='modulo_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.modulo_a'),
        ),
    ]
