# Generated by Django 4.2.3 on 2023-08-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_envio_remove_paqueteriames_modulo_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='id_operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envio',
            name='modulo_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.period'),
        ),
        migrations.DeleteModel(
            name='Modulo_A',
        ),
    ]
