# Generated by Django 4.2.3 on 2023-08-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_period_id_operador_alter_envio_modulo_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='id_operador',
            new_name='operador',
        ),
    ]
