# Generated by Django 4.2.3 on 2023-08-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_rename_id_operador_period_operador'),
    ]

    operations = [
        migrations.CreateModel(
            name='National_Shipment',
            fields=[
                ('id_National_Shipment', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.CharField(max_length=20)),
                ('number_docs', models.IntegerField()),
                ('number_packages', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='period',
            old_name='operador',
            new_name='id_operator',
        ),
        migrations.RenameModel(
            old_name='Form',
            new_name='Postal_Operator',
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
        migrations.AddField(
            model_name='national_shipment',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.postal_operator'),
        ),
    ]
