# Generated by Django 4.2.3 on 2023-08-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0018_national_shipment_id_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_National_Shipment',
            fields=[
                ('id_national_shipment', models.AutoField(primary_key=True, serialize=False)),
                ('number_docs', models.IntegerField()),
                ('number_packages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='T_Period',
            fields=[
                ('id_period', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='T_Year',
            fields=[
                ('id_year', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='period',
            name='id_operator',
        ),
        migrations.RenameModel(
            old_name='Postal_Operator',
            new_name='T_Postal_Operator',
        ),
        migrations.DeleteModel(
            name='National_Shipment',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.AddField(
            model_name='t_period',
            name='id_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_year'),
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='id_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_postal_operator'),
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='id_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_period'),
        ),
    ]
