# Generated by Django 4.2.3 on 2023-08-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_t_national_shipment_t_period_t_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_period',
            name='id_operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.t_postal_operator'),
            preserve_default=False,
        ),
    ]
