# Generated by Django 4.2.3 on 2023-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_t_period_id_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_national_shipment',
            name='file_nationals_shipments',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
