# Generated by Django 4.2.3 on 2023-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_t_national_shipment_file_nationals_shipments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_national_shipment',
            old_name='number_docs',
            new_name='een_packages_month1',
        ),
        migrations.RenameField(
            model_name='t_national_shipment',
            old_name='number_packages',
            new_name='een_packages_month2',
        ),
        migrations.RemoveField(
            model_name='t_national_shipment',
            name='file_nationals_shipments',
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='een_packages_month3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='een_packages_month4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='een_packages_month5',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='een_packages_month6',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='enn_docs_month1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='enn_docs_month2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='enn_docs_month3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='enn_docs_month4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='enn_docs_month5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_national_shipment',
            name='enn_docs_month6',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
