# Generated by Django 4.2.5 on 2023-09-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_rename_een_packages_month1_t_national_shipment_enn_packages_month1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_National_Billing',
            fields=[
                ('id_national_billing', models.AutoField(primary_key=True, serialize=False)),
                ('facn_docs_month1', models.IntegerField()),
                ('facn_docs_month2', models.IntegerField()),
                ('facn_docs_month3', models.IntegerField()),
                ('facn_docs_month4', models.IntegerField()),
                ('facn_docs_month5', models.IntegerField()),
                ('facn_docs_month6', models.IntegerField()),
                ('facn_packages_month1', models.IntegerField()),
                ('facn_packages_month2', models.IntegerField()),
                ('facn_packages_month3', models.IntegerField()),
                ('facn_packages_month4', models.IntegerField()),
                ('facn_packages_month5', models.IntegerField()),
                ('facn_packages_month6', models.IntegerField()),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_postal_operator')),
                ('id_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_period')),
            ],
        ),
        migrations.CreateModel(
            name='T_Local_Shipment',
            fields=[
                ('id_local_shipment', models.AutoField(primary_key=True, serialize=False)),
                ('enl_docs_month1', models.IntegerField()),
                ('enl_docs_month2', models.IntegerField()),
                ('enl_docs_month3', models.IntegerField()),
                ('enl_docs_month4', models.IntegerField()),
                ('enl_docs_month5', models.IntegerField()),
                ('enl_docs_month6', models.IntegerField()),
                ('enl_packages_month1', models.IntegerField()),
                ('enl_packages_month2', models.IntegerField()),
                ('enl_packages_month3', models.IntegerField()),
                ('enl_packages_month4', models.IntegerField()),
                ('enl_packages_month5', models.IntegerField()),
                ('enl_packages_month6', models.IntegerField()),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_postal_operator')),
                ('id_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_period')),
            ],
        ),
        migrations.CreateModel(
            name='T_Local_Billing',
            fields=[
                ('id_local_billing', models.AutoField(primary_key=True, serialize=False)),
                ('eni_docs_month1', models.IntegerField()),
                ('eni_docs_month2', models.IntegerField()),
                ('eni_docs_month3', models.IntegerField()),
                ('eni_docs_month4', models.IntegerField()),
                ('eni_docs_month5', models.IntegerField()),
                ('eni_docs_month6', models.IntegerField()),
                ('eni_packages_month1', models.IntegerField()),
                ('eni_packages_month2', models.IntegerField()),
                ('eni_packages_month3', models.IntegerField()),
                ('eni_packages_month4', models.IntegerField()),
                ('eni_packages_month5', models.IntegerField()),
                ('eni_packages_month6', models.IntegerField()),
                ('id_operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_postal_operator')),
                ('id_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.t_period')),
            ],
        ),
    ]
